model:
  n_feat: 256            # Number of features in U-Net
  epsilon: 0.0001          # Bound t for stability
  architecture: "flow"   # Architecture to use for the model

data:
  angle_path: "/pdo/users/jlupoiii/TESS/data/angles/angles_O11-54_data_dic.pkl"  # Path to angle data
  ccd_folder: "/pdo/users/djtufto/data/data_tess_4096_med_npy/"  # Folder containing processed images
  image_shape: [4096, 4096]  # Shape of the images
  patch_size: [128,128] # Shape of the patches; null for no patches
  repeat_factor: 1 # Iterate repeat_factor times over the dataset each epoch
  

# Used for sampling from generate.py
generation:
  model_path: "/pdo/users/djtufto/BEAM/model_outputs/sm_4096_med_sc/checkpoint_epoch_final_20250715_032027.pth" # Path to trained model checkpoint
  params_file: "data/params/params_100.pkl" # Path to orbital parameters (pickle file of shape [N, 12])
  n_datapoint: 2 # Number of datapoints (sets of parameters) to sample
  n_sample: 10 # Number of samples per datapoint
  num_timesteps: 5 # Number of timesteps to log including endpoints
  image_shape: [128, 128] # Shape of the images
  output_dir: "model_outputs/sm_4096_med_sc/generation_valid/" # Directory to save generated images
  ema: True # Use EMA weights for sampling
  guidance_scale: 1.4 # Guidance scale for sampling