model:
  n_feat: 128            # Number of features in U-Net
  epsilon: 0.0001          # Bound t for stability
  architecture: "noise"   # Architecture to use for the model
  channel_mults: [1,1,2,2,2]
  heads_at: [2,3,4]
  num_res: 2


data:
  angle_path: "/pdo/users/jlupoiii/TESS/data/angles/angles_O11-54_data_dic.pkl"  # Path to angle data
  ccd_folder: "/pdo/users/jlupoiii/TESS/data/processed_images_im4096x4096"  # Folder containing processed images
  background_path: null  # Folder containing background images
  image_shape: [4096,4096]  # Shape of the images
  patch_size: null # Shape of the patches; null for no patches
  repeat_factor: 1 # Iterate repeat_factor times over the dataset each epoch
  camera_number: '3'
  mean: 0.251619186104019 #Dataset mean (for normalization)
  std: 2.118188109008096 #Dataset standard deviation (for normalization)

# Used for sampling from generate.py (likelihood-only Langevin)
generation:
  model_path_star: /pdo/users/djtufto/BEAM/model_outputs/conditional_noise/checkpoint_epoch_final_20251008_175925.pth
  batch_size: 1
  num_timesteps: 10 # Number of snapshots to save along the trajectory
  output_dir: "model_outputs/likelihood_langevin/"
  ema: True # Use EMA weights for sampling
  star_mean: 0.08837062429384838 # Star model normalization mean
  star_std: 0.8176902707359797 # Star model normalization std
  num_langevin_steps: 30 # Number of Langevin iterations
  langevin_step_size: 0.5 # Step size for each Langevin update
