# Default configuration for BEAM model training

# Model parameters
model:
  n_feat: 128           # Number of features in U-Net
  epsilon: 0.0001          # Bound t for stability
  drop_prob: 0.1         # Dropout probability for classifier-free guidance
  architecture: "noise"   # Architecture to use for the model
  channel_mults: [1, 1, 2, 2, 2] # Channel multipliers for the U-Net: layer i has n_feat*channel_mults[i] features
  heads_at: [2,3,4] # Use attention at these indices in above channel_mults
  num_res: 2 # Number of residual blocks in each layer; if int, same for all layers

# Data parameters  
data:
  angle_path: /pdo/users/jlupoiii/TESS/data/angles/angles_O11-54_data_dic.pkl  # Path to angle data
  ccd_folder: /pdo/users/jlupoiii/TESS/data/processed_images_im256x256/
 # Folder containing processed images
  background_path: null
  image_shape: [256,256] # Shape of the images
  patch_size: null # Shape of the patches; null for no patches
  repeat_factor: 1 # Iterate repeat_factor times over the dataset each epoch
  # mean: 0.01978608595999928 #Dataset mean (for normalization)
  # std: 0.08876927679677006 #Dataset standard deviation (for normalization)
  mean: 0.008836520907439251 #Dataset mean (for normalization)
  std: 0.06466536033658327 #Dataset standard deviation (for normalization)
  # mean: 0.251619186104019 #Dataset mean (for normalization)
  # std: 2.118188109008096 #Dataset standard deviation (for normalization)
  camera_number: '3'
ema:
  beta: 0.9999 #EMA decay rate
  update_after_step: 10000 #Number of warmupsteps before updating EMA

optimizer:
  max_lr: 0.0001 #Maximum learning rate
  min_lr: 0.000001 #Minimum learning rate
  weight_decay: 0.00 #Weight decay
  warmup_steps: 1000 #Number of warmup steps
  grad_clip: 1.0 #Gradient clip

# Training parameters
training:
  n_epoch: 600          # Maximum number of epochs
  batch_size: 24         # Batch size
  patience: 1000          # Early stopping patience
  mixed_precision: True # Use BF16 for training

# Checkpoint parameters
checkpoint:
  save_model: True       # Save model checkpoints
  epoch_checkpoint: 50  # Save samples every N epochs
  checkpoint_gpu: 0      # GPU ID to use for checkpoints
  save_weights_only: False # Save only weights
  save_best_only: True # Save best model only at each checkpoint. 

load_checkpoint: null
  
# Weights & Biases parameters
wandb:
  enabled: True         # Enable W&B logging
  project: "beam-tess"   # W&B project name
  mode: "online"         # W&B mode (online, offline, disabled)
  log_freq: 20           # Log batch metrics every N batches (higher value = less traffic)
  log_samples_freq: 20   # Log sample images every N epochs
  log_model_freq: 100    # Log model weights every N epochs
  model_name: "Camera_3_256x256_test"     # Base name for the model and W&B run
  
# Paths
paths:
  save_dir: "model_outputs/cam3_256x256_test_star"  # Directory to save model and results
  
# Distributed training
distributed:
  world_size: 2       # Number of GPUs (null = auto-detect)
