# Default configuration for BEAM model training

# Model parameters
model:
  n_feat: 256            # Number of features in U-Net
  epsilon: 0.0001          # Bound t for stability
  drop_prob: 0.1         # Dropout probability for classifier-free guidance
  architecture: "flow"   # Architecture to use for the model
# Data parameters  
data:
  angle_path: "/pdo/users/djtufto/data_tess_512_nobg/angles/tess_angles_O11-54_data_dic.pkl"  # Path to angle data
  ccd_folder: "/pdo/users/djtufto/data_tess_512_nobg/ccd"  # Folder containing processed images
  image_shape: [512, 512]  # Shape of the images
  patch_size: [128, 128]  # Shape of the patches

ema:
  beta: 0.9999
  update_after_step: 1
  
# Training parameters
training:
  n_epoch: 1000          # Maximum number of epochs
  batch_size: 2         # Batch size
  lrate: 0.0003          # Learning rate
  patience: 1000          # Early stopping patience
  mixed_precision: True # Use FP16 for training

# Checkpoint parameters
checkpoint:
  save_model: False       # Save model checkpoints
  epoch_checkpoint: 75  # Save samples every N epochs
  checkpoint_gpu: 0      # GPU ID to use for checkpoints
  save_weights_only: False # Save only weights
  save_best_only: False # Save best model only at each checkpoint. 
  
# Weights & Biases parameters
wandb:
  enabled: True         # Enable W&B logging
  project: "beam-tess"   # W&B project name
  mode: "online"         # W&B mode (online, offline, disabled)
  log_freq: 50           # Log batch metrics every N batches (higher value = less traffic)
  log_samples_freq: 25   # Log sample images every N epochs
  log_model_freq: 50     # Log model weights every N epochs
  model_name: "SM-1024_patch_256"     # Base name for the model and W&B run
  
# Paths
paths:
  save_dir: "model_outputs/sm_1024_patch_256"  # Directory to save model and results
  
# Distributed training
distributed:
  world_size: 2       # Number of GPUs (null = auto-detect)
