# Default configuration for BEAM model training

# Model parameters
model:
  n_feat: 256            # Number of features in U-Net
  epsilon: 0.0001          # Bound t for stability
  drop_prob: 0.1         # Dropout probability for classifier-free guidance
  architecture: "flow"   # Architecture to use for the model
# Data parameters  
data:
  angle_path: "/pdo/users/djtufto/data/data_tess_4096_raw/angles/tess_angles_O11-54_data_dic.pkl"  # Path to angle data
  ccd_folder: /pdo/users/djtufto/data/data_tess_4096_med_npy/  # Folder containing processed images
  background_path: "/pdo/users/djtufto/data/data_tess_4096_raw/backgrounds/"
  image_shape: [4096,4096]  # Shape of the images
  patch_size: [128,128] # Shape of the patches; null for no patches
  repeat_factor: 1 # Iterate repeat_factor times over the dataset each epoch

ema:
  beta: 0.9999
  update_after_step: 10000
  
# Training parameters
training:
  n_epoch: 2000          # Maximum number of epochs
  batch_size: 24         # Batch size
  lrate: 0.0002          # Learning rate
  patience: 5000          # Early stopping patience
  mixed_precision: False # Use FP16 for training

# Checkpoint parameters
checkpoint:
  save_model: False       # Save model checkpoints
  epoch_checkpoint: 500  # Save samples every N epochs
  checkpoint_gpu: 0      # GPU ID to use for checkpoints
  save_weights_only: False # Save only weights
  save_best_only: True # Save best model only at each checkpoint. 
  
# Weights & Biases parameters
wandb:
  enabled: True         # Enable W&B logging
  project: "beam-tess"   # W&B project name
  mode: "online"         # W&B mode (online, offline, disabled)
  log_freq: 100           # Log batch metrics every N batches (higher value = less traffic)
  log_samples_freq: 50   # Log sample images every N epochs
  log_model_freq: 100     # Log model weights every N epochs
  model_name: "SM-4096-Med-SC"     # Base name for the model and W&B run
  
# Paths
paths:
  save_dir: "model_outputs/sm_4096_med_sc"  # Directory to save model and results
  
# Distributed training
distributed:
  world_size: null       # Number of GPUs (null = auto-detect)
